icecast:
  ports:
  - 8000:8000/tcp
  environment:
    ICECAST_SOURCE_PASSWORD: ${ICECAST_SOURCE_PASSWORD}
    ICECAST_ADMIN_PASSWORD: ${ICECAST_ADMIN_PASSWORD}
    ICECAST_PASSWORD: ${ICECAST_PASSWORD}
    ICECAST_RELAY_PASSWORD: ${ICECAST_RELAY_PASSWORD}
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: moul/icecast
  volumes:
  - /etc/icecast2/icecast.xml
  - /usr/share/icecast2/web/silence.mp3
  stdin_open: true
mopidy:
  ports:
  - 6600:6600/tcp
  - 6680:6680/tcp
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  command:
  - mopidy
  - -o
  - spotify/enabled=false
  - -o
  - gmusic/enabled=false
  - -o
  - soundcloud/enabled=false
  log_opt: {}
  image: wernight/mopidy
  links:
  - icecast:icecast
  volumes:
  - /var/lib/mopidy/media
  - /var/lib/mopidy/local
  - /var/lib/mopidy/.config/mopidy/mopidy.conf
